# Generated by Django 5.0.7 on 2024-07-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('image', models.ImageField(upload_to='medai/offerse/')),
                ('clicks', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updaet_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('image', models.ImageField(upload_to='medai/prodect/')),
                ('quintety', models.IntegerField(default=0)),
                ('cell_count', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updaet_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
